version: '3.4'
services:
  db:
    image: mongo:latest
    volumes:
      - ../mongo-dev/db:/data/db
      - ./dev-setup/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "${DB_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    command: mongod --auth