version: '3.4'
services:
  db:
    image: mongo:latest
    ports:
      - "${DB_PORT:-27017}:27017"
    networks:
      - candilib-network
    container_name: candilib_mongo
  api:
    build:
      context: ./
      dockerfile: Dockerfile-prod-api
    container_name: candilib_api
    depends_on:
      - db
    ports:
      - "${WEB_PORT:-8000}:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:27017/candilib
    networks:
      - candilib-network
networks:
  candilib-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450