# production mode
version: '3.4'
services:
  api:
    image: candilib_api:${APP_VERSION:-latest}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        proxy: ${http_proxy}
        no_proxy: ${no_proxy}
        npm_registry: ${NPM_REGISTRY}
    container_name: candilib_api
    ports:
      - "${WEB_PORT:-8000}:8000"
#    env_file:
#      - ${cnf:-.env}
    environment:
      NODE_ENV: production
      MONGO_URL: ${MONGO_URL:-mongodb://db:27017/candilib}
networks:
  default:
    external:
      name: ${APP}-network
